version: "3"
 
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: "nginx-proxy"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/gyser/certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./config/nginx/conf.d:/etc/nginx/conf.d:rw
    networks:
      - "nginx-proxy-net"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
 
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: "letsencrypt"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/gyser/certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
      - dhparam:/etc/nginx/dhparam
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=gyser.world@gmail.com
    depends_on:
      - "nginx-proxy"
    networks:
      - "nginx-proxy-net"
 
volumes:
  vhost:
  html:
  dhparam:
 
networks:
 nginx-proxy-net:
  external: true
